#ifndef BASKETPWDLIBS_GLOBAL_H
#define BASKETPWDLIBS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BASKETPWD_LIBRARY)
#  define BASKETPWDLIBSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BASKETPWDLIBSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BASKETPWDLIBS_GLOBAL_H
