#!/bin/bash

APP_NAME=basketpwd
APP_VERSION=`cat ../$APP_NAME.pro | grep VERSION | head -n1 | awk '{print $3}'`

cd ../..
cp -f -r ./$APP_NAME ./$APP_NAME-$APP_VERSION
rm -rf ./$APP_NAME-$APP_VERSION/.git
tar cfj $APP_NAME-$APP_VERSION.tar.bz2 ./$APP_NAME-$APP_VERSION
rm -rf ./$APP_NAME-$APP_VERSION
